#pragma once

#include "macro.h"

#define CHT_PP_DECLARE_COMBO_ITEM(_1, _2, GROUP_SEQ_)    \
    DECLARE_ENUM_GROUP(BOOST_PP_CAT(ADD_ENUM_ELEM_1 GROUP_SEQ_, _END))

////////////////////////////////////////////////////////////////////////////////
// COMBO
////////////////////////////////////////////////////////////////////////////////

#define CHT_PP_DECLARE_COMBO_FORWARDER(NAME_)    \
    CHT_PP_ENUM_DECLARE_BITWISE(NAME_)  \
    CHT_PP_ENUM_DECLARE_IO(NAME_)

#define CHT_PP_DECLARE_COMBO_INNER_FORWARDER(NAME_)    \
    CHT_PP_ENUM_INNER_DECLARE_BITWISE(NAME_)  \
    CHT_PP_ENUM_INNER_DECLARE_IO(NAME_)

#define CHT_PP_DECLARE_COMBO_GROUPS(_1, NAME_, I_, GROUP_SEQ_)    \
    BOOST_PP_CAT    \
    (   \
        BOOST_PP_COMMA_IF(I_),     \
        CHT_PP_DECLARE_COMBO_GROUP   \
        (   \
            BOOST_PP_SEQ_SIZE(GROUP_SEQ_), \
            NAME_,  \
            BOOST_PP_CAT(ADD_RECORD_ELEM_1 GROUP_SEQ_, _END)  \
        )   \
    )

#define CHT_PP_DECLARE_COMBO_GROUP(GROUP_SIZE_, NAME_, GROUP_SEQ_)    \
        utils_type::group_t<GROUP_SIZE_> {  \
            BOOST_PP_SEQ_FOR_EACH(CHT_PP_DECLARE_COMBO_RECORD, NAME_, GROUP_SEQ_)  \
        }

#define CHT_PP_DECLARE_COMBO_RECORD(_1, NAME_, ITEM_)    \
    utils_type::record_type     \
    {   \
        ITEM_    \
        BOOST_PP_COMMA()    \
        BOOST_PP_CAT(BOOST_PP_STRINGIZE(ITEM_), sv)   \
        BOOST_PP_COMMA()    \
        BOOST_PP_CAT(BOOST_PP_WSTRINGIZE(ITEM_), sv)   \
    }   \
    BOOST_PP_COMMA()

////////////////////////////////////////////////////////////////////////////////
#define CHT_PP_DECLARE_COMBO_RTTI(NAME_, GROUP_SEQ_, ...) \
    CHT_PP_BEGIN_DECLARE_ENUM(NAME_) \
        BOOST_PP_SEQ_FOR_EACH(CHT_PP_DECLARE_COMBO_ITEM, ~, GROUP_SEQ_) \
        DECLARE_ENUM_GROUP(BOOST_PP_CAT(ADD_ENUM_ELEM_1 __VA_ARGS__, _END)) \
    CHT_PP_END_DECLARE_ENUM()

#define CHT_PP_DECLARE_COMBO(NAME_, GROUP_SEQ_, ...) \
    CHT_PP_DECLARE_COMBO_RTTI(NAME_, GROUP_SEQ_, __VA_ARGS__) \
    CHT_PP_BEGIN_DECLARE_ENUM_META(NAME_, combo) \
        BOOST_PP_SEQ_FOR_EACH_I(CHT_PP_DECLARE_COMBO_GROUPS, NAME_, GROUP_SEQ_) \
    CHT_PP_END_DECLARE_ENUM_META()  \
    CHT_PP_DECLARE_COMBO_FORWARDER(NAME_)

#define CHT_PP_DECLARE_COMBO_INNER(NAME_, GROUP_SEQ_, ...) \
    CHT_PP_DECLARE_COMBO_RTTI(NAME_, GROUP_SEQ_, __VA_ARGS__) \
    CHT_PP_BEGIN_DECLARE_ENUM_META_INNER(NAME_, combo) \
        BOOST_PP_SEQ_FOR_EACH_I(CHT_PP_DECLARE_COMBO_GROUPS, NAME_, GROUP_SEQ_) \
    CHT_PP_END_DECLARE_ENUM_META()  \
    CHT_PP_DECLARE_COMBO_INNER_FORWARDER(NAME_)

////////////////////////////////////////////////////////////////////////////////
#define CHT_PP_DECLARE_COMBO_BASE_RTTI(NAME_, BASE_, GROUP_SEQ_, ...) \
    CHT_PP_BEGIN_DECLARE_ENUM_BASE(NAME_, BASE_) \
        BOOST_PP_SEQ_FOR_EACH(CHT_PP_DECLARE_COMBO_ITEM, ~, GROUP_SEQ_) \
        DECLARE_ENUM_GROUP(BOOST_PP_CAT(ADD_ENUM_ELEM_1 __VA_ARGS__, _END)) \
    CHT_PP_END_DECLARE_ENUM()

#define CHT_PP_DECLARE_COMBO_BASE(NAME_, BASE_, GROUP_SEQ_, ...) \
    CHT_PP_DECLARE_COMBO_BASE_RTTI(NAME_, BASE_, GROUP_SEQ_, __VA_ARGS__) \
    CHT_PP_BEGIN_DECLARE_ENUM_META(NAME_, combo) \
        BOOST_PP_SEQ_FOR_EACH_I(CHT_PP_DECLARE_COMBO_GROUPS, NAME_, GROUP_SEQ_) \
    CHT_PP_END_DECLARE_ENUM_META()  \
    CHT_PP_DECLARE_COMBO_FORWARDER(NAME_)

#define CHT_PP_DECLARE_COMBO_INNER_BASE(NAME_, BASE_, GROUP_SEQ_, ...) \
    CHT_PP_DECLARE_COMBO_BASE_RTTI(NAME_, BASE_, GROUP_SEQ_, __VA_ARGS__) \
    CHT_PP_BEGIN_DECLARE_ENUM_META_INNER(NAME_, combo) \
        BOOST_PP_SEQ_FOR_EACH_I(CHT_PP_DECLARE_COMBO_GROUPS, NAME_, GROUP_SEQ_) \
    CHT_PP_END_DECLARE_ENUM_META()  \
    CHT_PP_DECLARE_COMBO_INNER_FORWARDER(NAME_)

////////////////////////////////////////////////////////////////////////////////
#define CHT_PP_ADAPT_COMBO(NAME_, GROUP_SEQ_) \
    CHT_PP_BEGIN_DECLARE_ENUM_META(NAME_, combo) \
        BOOST_PP_SEQ_FOR_EACH_I(CHT_PP_DECLARE_COMBO_GROUPS, NAME_, GROUP_SEQ_) \
    CHT_PP_END_DECLARE_ENUM_META() \
    CHT_PP_DECLARE_COMBO_FORWARDER(NAME_)

////////////////////////////////////////////////////////////////////////////////
// COMBO_CLASS
////////////////////////////////////////////////////////////////////////////////

#define CHT_PP_DECLARE_COMBO_CLASS_FORWARDER(NAME_)    \
    CHT_PP_ENUM_DECLARE_BITWISE(NAME_)  \
    CHT_PP_ENUM_DECLARE_EQUALITY_COMPARABLE(NAME_)   \
    CHT_PP_ENUM_DECLARE_IO(NAME_)

#define CHT_PP_DECLARE_COMBO_CLASS_INNER_FORWARDER(NAME_)    \
    CHT_PP_ENUM_INNER_DECLARE_BITWISE(NAME_)  \
    CHT_PP_ENUM_INNER_DECLARE_TOTALLY_ORDERED(NAME_)   \
    CHT_PP_ENUM_INNER_DECLARE_IO(NAME_)

#define CHT_PP_DECLARE_COMBO_CLASS_GROUPS(_1, NAME_, I_, GROUP_SEQ_)    \
    BOOST_PP_CAT    \
    (   \
        BOOST_PP_COMMA_IF(I_),     \
        CHT_PP_DECLARE_COMBO_CLASS_GROUP   \
        (   \
            BOOST_PP_SEQ_SIZE(GROUP_SEQ_), \
            NAME_,  \
            BOOST_PP_CAT(ADD_RECORD_ELEM_1 GROUP_SEQ_, _END)  \
        )   \
    )

#define CHT_PP_DECLARE_COMBO_CLASS_GROUP(GROUP_SIZE_, NAME_, GROUP_SEQ_)    \
        utils_type::group_t<GROUP_SIZE_> {  \
            BOOST_PP_SEQ_FOR_EACH(CHT_PP_DECLARE_COMBO_CLASS_RECORD, NAME_, GROUP_SEQ_)  \
        }

#define CHT_PP_DECLARE_COMBO_CLASS_RECORD(_1, NAME_, ITEM_)    \
    utils_type::record_type     \
    {   \
        BOOST_PP_CAT(BOOST_PP_CAT(NAME_, ::), ITEM_)    \
        BOOST_PP_COMMA()    \
        BOOST_PP_CAT(BOOST_PP_STRINGIZE(ITEM_), sv)   \
        BOOST_PP_COMMA()    \
        BOOST_PP_CAT(BOOST_PP_WSTRINGIZE(ITEM_), sv)   \
    }   \
    BOOST_PP_COMMA()

////////////////////////////////////////////////////////////////////////////////
#define CHT_PP_DECLARE_COMBO_CLASS_RTTI(NAME_, GROUP_SEQ_, ...) \
    CHT_PP_BEGIN_DECLARE_ENUM_CLASS(NAME_) \
        BOOST_PP_SEQ_FOR_EACH(CHT_PP_DECLARE_COMBO_ITEM, ~, GROUP_SEQ_) \
        DECLARE_ENUM_GROUP(BOOST_PP_CAT(ADD_ENUM_ELEM_1 __VA_ARGS__, _END)) \
    CHT_PP_END_DECLARE_ENUM()

#define CHT_PP_DECLARE_COMBO_CLASS(NAME_, GROUP_SEQ_, ...) \
    CHT_PP_DECLARE_COMBO_CLASS_RTTI(NAME_, GROUP_SEQ_, __VA_ARGS__) \
    CHT_PP_BEGIN_DECLARE_ENUM_META(NAME_, combo) \
        BOOST_PP_SEQ_FOR_EACH_I(CHT_PP_DECLARE_COMBO_CLASS_GROUPS, NAME_, GROUP_SEQ_) \
    CHT_PP_END_DECLARE_ENUM_META()  \
    CHT_PP_DECLARE_COMBO_CLASS_FORWARDER(NAME_)

#define CHT_PP_DECLARE_COMBO_CLASS_INNER(NAME_, GROUP_SEQ_, ...) \
    CHT_PP_DECLARE_COMBO_CLASS_RTTI(NAME_, GROUP_SEQ_, __VA_ARGS__) \
    CHT_PP_BEGIN_DECLARE_ENUM_META_INNER(NAME_, combo) \
        BOOST_PP_SEQ_FOR_EACH_I(CHT_PP_DECLARE_COMBO_CLASS_GROUPS, NAME_, GROUP_SEQ_) \
    CHT_PP_END_DECLARE_ENUM_META()  \
    CHT_PP_DECLARE_COMBO_CLASS_INNER_FORWARDER(NAME_)

////////////////////////////////////////////////////////////////////////////////
#define CHT_PP_DECLARE_COMBO_CLASS_BASE_RTTI(NAME_, BASE_, GROUP_SEQ_, ...) \
    CHT_PP_BEGIN_DECLARE_ENUM_CLASS_BASE(NAME_, BASE_) \
        BOOST_PP_SEQ_FOR_EACH(CHT_PP_DECLARE_COMBO_ITEM, ~, GROUP_SEQ_) \
        DECLARE_ENUM_GROUP(BOOST_PP_CAT(ADD_ENUM_ELEM_1 __VA_ARGS__, _END)) \
    CHT_PP_END_DECLARE_ENUM()

#define CHT_PP_DECLARE_COMBO_CLASS_BASE(NAME_, BASE_, GROUP_SEQ_, ...) \
    CHT_PP_DECLARE_COMBO_CLASS_BASE_RTTI(NAME_, BASE_, GROUP_SEQ_, __VA_ARGS__) \
    CHT_PP_BEGIN_DECLARE_ENUM_META(NAME_, combo) \
        BOOST_PP_SEQ_FOR_EACH_I(CHT_PP_DECLARE_COMBO_CLASS_GROUPS, NAME_, GROUP_SEQ_) \
    CHT_PP_END_DECLARE_ENUM_META()  \
    CHT_PP_DECLARE_COMBO_CLASS_FORWARDER(NAME_)

#define CHT_PP_DECLARE_COMBO_CLASS_INNER_BASE(NAME_, BASE_, GROUP_SEQ_, ...) \
    CHT_PP_DECLARE_COMBO_CLASS_BASE_RTTI(NAME_, BASE_, GROUP_SEQ_, __VA_ARGS__) \
    CHT_PP_BEGIN_DECLARE_ENUM_META_INNER(NAME_, combo) \
        BOOST_PP_SEQ_FOR_EACH_I(CHT_PP_DECLARE_COMBO_CLASS_GROUPS, NAME_, GROUP_SEQ_) \
    CHT_PP_END_DECLARE_ENUM_META()  \
    CHT_PP_DECLARE_COMBO_CLASS_INNER_FORWARDER(NAME_)

////////////////////////////////////////////////////////////////////////////////
#define CHT_PP_ADAPT_COMBO_CLASS(NAME_, GROUP_SEQ_) \
    CHT_PP_BEGIN_DECLARE_ENUM_META(NAME_, combo) \
        BOOST_PP_SEQ_FOR_EACH_I(CHT_PP_DECLARE_COMBO_CLASS_GROUPS, NAME_, GROUP_SEQ_) \
    CHT_PP_END_DECLARE_ENUM_META() \
    CHT_PP_DECLARE_COMBO_CLASS_FORWARDER(NAME_)

#include "op.h"
#include "traits.h"